### ISSUE TITLE
[Feature]: Operation to read from environment variables

### ISSUE THREAD

**Issue by keymon** [geofffranks/spruce#107]
It would be great to have an operation to read environment variables, so that you can override some values easy.

Something like:

```
server:
  aws_secret: (( env(AWS_SECRET) ))
  url; (( env(SERVER_URL) || 'localhost' ))
```

What do you think?

**Comment by jhunt** [comment]
Would this work:

```
server:
  aws_secret: (( env "AWS_SECRET" ))
  url: (( env "SERVER_URL" "localhost" ))
```

?

**Comment by keymon** [comment]
Are you asking if I knew that is already implemented or if the syntax works for me?

I think the syntax is perfect. 

If it was implemented, sorry for reporting, I did not see it before, I will check it out later (not in the right place now)

**Comment by jhunt** [comment]
Nope, not yet implemented.  I just saw this issue while I was fixing a static_ips bug, and thought I'd take a crack at it.  Should be a PR forthcoming today, and a release a few days after.  :smile:

**Comment by keymon** [comment]
Cool, thx !!

**Comment by jhunt** [comment]
After more discussion, we came up with this muuuuch better approach that doesn't confuse @longnguyen11288 

```
envs:
- (( grab $HOME ))
- (( grab $HOME || "/home" ))
- (( concat $HOME "/bin" ))
- (( concat $HOME || "/home" "bin" ))
```

The first call will fail if $HOME is not set.  The second will use "/home" instead.

The syntax also works with other operators like `(( concat ... ))`

**Comment by keymon** [comment]
\o/
