### ISSUE TITLE
Is spruce obsolete now that bosh links have landed?

### ISSUE THREAD

**Issue by mavenraven** [geofffranks/spruce#108]
http://bosh.io/docs/links.html cc @drnic

**Comment by longnguyen11288** [comment]
i still it's useful to have smaller manifest then larger manifest and links requires changes to boshrelease

**Comment by drnic** [comment]
Will bosh links make bosh manifests better? Yes. Will you still like to compose them from modular YAML? I believe so.

Also I use spruce outside of bosh manifest creation (e.g. concourse manifest creation).

**Comment by jhunt** [comment]
Spruce is also still a vital part of things like Genesis: https://github.com/starkandwayne/genesis
