### ISSUE TITLE
safe operator to generate passwords and ssh keys

### ISSUE THREAD

**Issue by longnguyen11288** [geofffranks/spruce#126]
Can we add safe operator to spruce that is similar to what https://github.com/jhunt/safe does?

**Comment by longnguyen11288** [comment]
How does this workflow sound

## Generating ssh keys

```
key: (( safe ssh "secret/ssh" ))
```
if  key isn't there generates ssh key for private and public key and added `:public` and `:private` to path respectively else return back value from vault as 
```
key:
  public_key: <public key>
  private_key: <private key>
```


## Generating secrets

```
secret: (( safe random 32 "secret/password" ))
```

if secret doesn't exist, generate 32 char password else retrieve from vault 

@geofffranks @jhunt thoughts?

**Comment by jhunt** [comment]
I don't like the idea of libifying safe right now -- still too new / unstable / malleable at this point.

What if, for the project that you need this for (blacksmith?) you just incorporate a safe script and run as a pre-exec before you generate the manifest?

**Comment by longnguyen11288** [comment]
hmm ok, we can talk about more ideas

**Comment by geofffranks** [comment]
Sounds like this is being done at a level above spruce. closing

**Comment by scottillogical** [comment]
Even though bosh2 does something like this, I/we still have projects that use spruce and this would be very helpful for those!
