### ISSUE TITLE
Sorting: name should go first

### ISSUE THREAD

**Issue by giner** [geofffranks/spruce#136]
Currently the resulted manifest is quite confusing because everything seems to be sorted alphabetically and "name" never goes first. It might be convenient to have name was going first if there is one.

**Comment by jhunt** [comment]
Have you looked at https://github.com/cloudfoundry-community/humanize-manifest ?

**Comment by doublespaces** [comment]
> Have you looked at https://github.com/cloudfoundry-community/humanize-manifest ?

Concourse uses the key 'task' which I find is usually listed last and further adds to the complexity in reviewing configurations. There is no way to add some custom weights to these keys?
