### ISSUE TITLE
When merging array with injected entries, append/prepend doesn't work

### ISSUE THREAD

**Issue by liuweichu** [geofffranks/spruce#148]
Example:

```
$ spruce -v
spruce - Version 1.6.0

$ cat /tmp/a

---
dict1:
  array1:
  - 1
  - 2

dict2:
  inject: (( inject dict1 ))
  array1:
  - (( prepend ))
  - 3
  - 4

$ spruce merge /tmp/a
dict1:
  array1:
  - 1
  - 2
dict2:
  array1:
  - 1
  - 2
  - 3
  - 4

$ cat /tmp/a

---
dict1:
  array1:
  - 1
  - 2

dict2:
  inject: (( inject dict1 ))
  array1:
  - (( append ))     # <- changed to append, but output is the same
  - 3
  - 4

$ spruce merge /tmp/a
dict1:
  array1:
  - 1
  - 2
dict2:
  array1:
  - 1
  - 2
  - 3
  - 4
```

It will be nice that this array merging honors the prepend/append

**Comment by jhunt** [comment]
Here's a minimal test case on play.spruce.cf: http://play.spruce.cf/#43e94adf3d58d29413f4cd2f5cb8a1f6

**Comment by giner** [comment]
Actually not only this.

Arrays are merged differently depending on how we merge them, by merging different files or with inject: http://play.spruce.cf/#3b90ce88948c4b256111314be6562249

With inject none of delete, inline, append or prepend work.

**Comment by geofffranks** [comment]
Closing as stale
