### ISSUE TITLE
Minor: play.spruce.cf throws js error

### ISSUE THREAD

**Issue by eric-cartman** [geofffranks/spruce#152]
When trying to run some spruce example via `play.spruce.cf` I get the following js-error (using FireFox 45.2.0)
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
.success()
 app.js:167
m.Callbacks/j()
 jquery.js:2
m.Callbacks/k.fireWith()
 jquery.js:2
x()
 jquery.js:5
.send/b()
 jquery.js:5
```

@jhunt.I really like the idea of the tool, therefore I just wanted to let you know.

**Comment by geofffranks** [comment]
Can you proved the example yaml that was causing the JS error?

**Comment by jhunt** [comment]
Thanks for the kind words!

Can you provide more information that I can use to reproduce this JSON issue?  The code in question would balk if the server ever gave back bad JSON, but short of a non-200 response, I can't think of a situation (off the top of my head, at least) where it would do so.

**Comment by eric-cartman** [comment]
@geofffranks && @jhunt 
Here are the details:
- I opened play.spruce.cf
- took the default values 
`--- # jobs.yml
jobs:
- name: staticIP_z1
  instances: 3
  networks:
  - name: net1
    static_ips: (( static_ips(0, 2, 4) ))
- name: api_z1
  instances: 3
  networks:
  - name: net1
    static_ips: (( static_ips(1, 3, 5) ))
--- # properties.yml
properties:
  staticIP_servers: (( grab jobs.staticIP_z1.networks.net1.static_ips ))
  api_servers: (( grab jobs.api_z1.networks.net1.static_ips ))
--- # networks.yml
networks:
- name: net1
  subnets:
  - cloud_properties: random
    static:
    - 192.168.0.2 - 192.168.0.10`
- Clicked the "Merge" button
-> nothing happens
-> looking into js.console (FF) I can see the JS error mentioned above

I attached a screenshot of my browser, just in case you are wondering if I changed parameters or something alike
![selection_044](https://cloud.githubusercontent.com/assets/20593946/17100134/f22fedf8-526c-11e6-952d-907218846b93.png)

Please let me know if I can help you or if you need more information.

**Comment by jhunt** [comment]
Can you get a dump of the HTTP traffic to/from the play.spruce.cf web server while this problem manifests?  Either pcaps (tcpdump) or screenshots of something like Firebug should be sufficient (if the request / response payloads are visible)

**Comment by eric-cartman** [comment]
@jhunt && @geofffranks:

I did some digging, including forcing fellow spruce guys to open play.spruce.cf and it turned out that the issue mentioned above is a company network issue: non of us was able to use play.spruce.cf within our company network (using different Browsers), yet opening it from home and playing around with it works like a charm.
Hence I am closing the issue.

greetings,
t.
