### ISSUE TITLE
functions can refer to unrealized values

### ISSUE THREAD

**Issue by liuweichu** [geofffranks/spruce#155]
If a value that is a to-be-realized value `(( ... ))`, when it get passed to another function as parameter, it can be either resolvd as the literal string `(( ... ))` or the correct value, depending on the actual realization order.

http://play.spruce.cf/#563d40ac2465f3bc20545b1d2db2ed12

I think when function read values, it should check if the value is realized or not.

**Comment by jhunt** [comment]
This is a data-flow problem in argument analysis.  Since the immediate value is not an operator, it is not put into the DAG.  We really ought to recursively resolve the dependencies in the data flow analysis stage.

**Comment by geofffranks** [comment]
This appears to be fixed as of #165. once a release is cut, we can close this i think.

**Comment by liuweichu** [comment]
Looking forward to the new version 😃

**Comment by geofffranks** [comment]
1.8.1 is out, give it a shot :)

**Comment by liuweichu** [comment]
Will close since it is fixed in 1.8.1

Thanks
