### ISSUE TITLE
Handle common backslash-escape sequences in literal strings

### ISSUE THREAD

**Issue by jhunt** [geofffranks/spruce#175]
We should be able to turn the following escape sequences into their ASCII equivalents:

- `\n` -> newline (`0xa`)
- `\r` -> carriage return
- `\t` -> tab character
- `\\` -> literal backslash
- `\"` -> literal double quote
- `\'` -> literal single quote

This will allow us to do the following:

```
lines: (( join "\n" meta.lists ))
```

**Comment by thomasmmitchell** [comment]
cases to consider:
`"\""`
`"\"`

**Comment by jhunt** [comment]
I updated the initial comment.
