### ISSUE TITLE
Array `delete` operations shouldn't fail silently

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#202]
Given `- (( delete myname ))`, spruce should either auto-translate `myname` into a string, or error that it wasn't specified as a string

Currently, it deletes index-0 of the array  (`- (( delete "myname" ))` deletes the correct element).

**Comment by thomasmmitchell** [comment]
Can you give an example?

`- (( delete myname ))` doesn't appear to fail silently (although, it does give a confusing error message): http://play.spruce.cf/#e2123d73476b412b8fa3afef8eebf69a

**Comment by geofffranks** [comment]
Unfortunately, I don't have the example anymore, so I have to go with "lets fix the example you linked"
