### ISSUE TITLE
Optional passthrough for unresolved symbols

### ISSUE THREAD

**Issue by CAFxX** [geofffranks/spruce#209]
I would like to suggest to add a mode of execution in which unresolved symbols do not cause an error to be reported and the merge to fail but are instead "passed-thru" to the output.

Specifically something like:
```
msg: (( concat greeting what ))
```
merged with 
```
greeting: "hello"
```
would yield
```
msg: (( concat "hello" what ))
```
instead of an exception.

I haven't considered all the implications of such a design though (e.g. I would imagine the "partial evaluation" would be restricted to only scalar values, since it would be hard to embed an array/dict in a spruce expression).

**Comment by geofffranks** [comment]
@CAFxX What are you trying to accomplish with this? Building stub spruce files to be merged later?

**Comment by CAFxX** [comment]
@geofffranks in a nuthell, yes

**Comment by geofffranks** [comment]
Would the --skip-eval, (( defer )), and ((!property)) possibilities be enough for this?

**Comment by geofffranks** [comment]
Closing, since there've been no responses. If the above options don't solve this, feel free to reopen
