### ISSUE TITLE
--skip-eval for parameters

### ISSUE THREAD

**Issue by FaKeller** [geofffranks/spruce#211]
Using `--skip-eval` with `(( param ))` constructs throws an error. For example:

```sh
$ cat demo.yml
properties:
  diego: (( grab meta.diego_enabled ))
  poll-interval: (( param "Interval in seconds to poll Pivotal network" ))
```

yields the following error:

```sh
spruce merge --skip-eval demo.yml
1 error(s) detected:
 - $.properties.poll-interval: Interval in seconds to poll Pivotal network
```

Is this by design or a bug?

**Comment by geofffranks** [comment]
Well, `skip-eval` skips the evaluate phase, and params are done in a separate phase, so i guess technically, that's by design, but it does seem like a potentially undesirable behavior.

**Comment by geofffranks** [comment]
@FaKeller does the `(( defer ))` operator allow you to do what you're trying to do? You would probably need to `(( defer ))` all the calls you want to defer, and stop using `--skip-eval`

**Comment by qu1queee** [comment]
@geofffranks same case with the `(( inject * ))` command. I know its because this gets executed after the merge phase, however its kind of a problem not to be able to skip the `inject`.  Any ideas on how to solve this?(design change?).

**Comment by FaKeller** [comment]
Thank you @geofffranks for solving this 👍
