### ISSUE TITLE
Add (( rename )) operator to allow name changes of named-array entries

### ISSUE THREAD

**Issue by HeavyWombat** [geofffranks/spruce#214]
Like [discussed](https://cloudfoundry.slack.com/archives/C26FF0W5B/p1496998351274106,) in the Slack channel, it would be great to have a possibility to rename an array entry that is `name`, `key`, or `id` based. The most favorable implementation would allow an end-user to both use the old and new names (new names introduced by a `- (( rename "old" "new" ))` at the same time during the merge. However, at the end only the last new name will be used in the generated YAML.

The test cases have to include the following rough scenarios:
- Combination of `rename` with the array modification operations: `append`, `prepend`, `inline`, ...
- Multiple `rename` on the same structure
- Combination with `inject`
- Usage of `grab` and `concat` with old, new and combination of old and new names
- Using `prune`, both the command line option and in-file `prune`

**Comment by thomasmmitchell** [comment]
For the sake of having a spec to look at and discuss, can you, by any chance, post a YAML before/after showing the expected behavior with the operator?

**Comment by jhunt** [comment]
I still think it would be nice to support it first-class in spruce, without dropping down to go-patch, specifically for the aliasing support.

**Comment by HeavyWombat** [comment]
I had only a quick look at the new go-patch feature. I think I am still in favour for a separate `(( rename ))` operator. I am currently not working that much, but I try to update this issue with the YAML before and after examples like @thomasmmitchell suggested.
