### ISSUE TITLE
credhub compatibility

### ISSUE THREAD

**Issue by poblin-orange** [geofffranks/spruce#216]
Hello,
im trying to introduce credhub in our spruce/concourse based deployment.
Seems that credhub place holder syntax ((var)) is not accepted by spruce.
Is there way to workaround this issue.
Id like to keep our spruce templating and use credhub for certs and password generation

**Comment by jhunt** [comment]
I believe @thomasmmitchell is working on a `(( defer ... ))` operator that will work like a quoting operator to pass through its arguments untouched, with the enclosing `(( ... ))`.  That should do what you want.  I don't see a Github issue for it though...

**Comment by thomasmmitchell** [comment]
Figured it was part of an initiative related to #209 
If you want, I can make it it's own ticket. Also, I still think that having a flag to accept the ((var)) syntax would be helpful, both for Credhub and Concourse, and that maybe that should be implemented.

**Comment by poblin-orange** [comment]
as part of a slack discussion, spiff just ignores this syntax ((!password)).
https://cloudfoundry.slack.com/archives/C3EN0BFC0/p1499101056431229

Could we expect the same mechanism for spruce ?

**Comment by jhunt** [comment]
Already implemented (since v0) because Spruce is fairly stringent with its operator inputs.  Submitted #217 to document and test.

**Comment by poblin-orange** [comment]
Just tested end to end the ((!xxx)) syntax. Ignored by spruce and spiff.
Thks
