### ISSUE TITLE
spruce playground is not working at all

### ISSUE THREAD

**Issue by andrew-edgar** [geofffranks/spruce#225]
With the newest browsers I hit "merge" and nothing happens.

I'm seeing this issue in the Chrome developer tools ...

```
VM47:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.success (app.js:172)
    at j (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at x (jquery.js:5)
    at XMLHttpRequest.b (jquery.js:5)
success @ app.js:172
j @ jquery.js:2
fireWith @ jquery.js:2
x @ jquery.js:5
b @ jquery.js:5
XMLHttpRequest.send (async)
send @ jquery.js:5
ajax @ jquery.js:5
(anonymous) @ app.js:167
dispatch @ jquery.js:4
r.handle @ jquery.js:4
```

I was not able to run any tests in the playground because of this.

**Comment by geofffranks** [comment]
Hmm. It's working for me. Any chance there's traffic being blocked by a company firewall? This sounds similar to https://github.com/geofffranks/spruce/issues/152

**Comment by geofffranks** [comment]
@andrew-edgar is this still an issue?
