### ISSUE TITLE
How can I concat the values of multiple files?

### ISSUE THREAD

**Issue by Anthonyhawkins** [geofffranks/spruce#227]
**Scenario:** Two environment variables each containing the path to a pem file.  I need the values of both files to be the single value of the `cert:` key. How can I do this/is it possible? 

Obviously this example doesn't work but is used to illustrate what I'm aiming for. 
```yaml
cert: (( file $DOCKER_CA_PATH $S3_CA_PATH ))
```

**Comment by jhunt** [comment]
You could try something like this (inspired by http://play.spruce.cf/#2bbf3bc4ecd6292166f95593a6ca60ae):

```
---
meta:
  certs:
    docker_ca: (( file $DOCKER_CA_PATH ))
    s3_ca:     (( file $S3_CA_PATH ))

cert: (( concat meta.certs.docker_ca meta.certs.c3_ca ))
```

(unfortunately, play.spruce.cf doesn't have a lot of options when it comes to the `(( file ... ))` operator)

**Comment by Anthonyhawkins** [comment]
That's exactly what I ended up going with after more tinkering.  Thank you!
