### ISSUE TITLE
Support concourse secrets

### ISSUE THREAD

**Issue by willejs** [geofffranks/spruce#228]
Concourse now supports hashicorp vault as a secret backend, however, the way to specify a secret is to wrap it in `(( ))` obviously this interferes with your template formatting and is incompatible, so somehow this should be resolved?

**Comment by geofffranks** [comment]
We usually handle this by using the format outlined here: https://github.com/geofffranks/spruce/blob/master/doc/integrating-with-credhub.md

Will this work for you?

**Comment by willejs** [comment]
@geofffranks 👍
