### ISSUE TITLE
It would be great if I could signal ENV variables are to be grab|inject|etc as a boolean

### ISSUE THREAD

**Issue by DRuggeri** [geofffranks/spruce#231]
As the title says, if I have an environment variable (or a literal) that contains the strings "true" or "false", it would be cool if I could signal to spruce that the value should be treated as a boolean. Perhaps creating a new boolean operator that will accept the substitution result as only "true" or "false" and error otherwise. Thoughts welcome

**Comment by sorenh** [comment]
Accidentally called out this bug in the commit message of my patch. I don't actually have a fix for this one.
