### ISSUE TITLE
(( grab $var )) doesn't seem to work in all contexts

### ISSUE THREAD

**Issue by jdennaho** [geofffranks/spruce#239]
grab works in YML if its of this form:

element: (( grab $env_var ))

it does not fill in environment variables in other circumstances:

element:
   - statictext(( grab $env_var ))morestatictext

or

element: statictext(( grab $env_var ))morestatictext

**Comment by geofffranks** [comment]
The concat operator should get you what you're looking for here: https://github.com/geofffranks/spruce/blob/master/doc/operators.md#-concat-
