### ISSUE TITLE
consider (( delete )) idempotence

### ISSUE THREAD

**Issue by thomasmitchell** [geofffranks/spruce#240]
So, when I worked on the delete operator, the idea was that it should "inform" you (by implosion) if you're trying to delete an entry which isn't present in the array, because you're most likely doing something wrong.

Until somebody wrote genesis 2. And now subkits are maybe possibly sometimes present? And so deletions need to maybe possibly sometimes happen. My workaround has been just making a stub entry so that there's _something_ to delete

```
mylist:
- name: foo
- (( delete "foo" ))
```
 
In the long run, maybe there should either be a flag for making delete idempotent, or maybe it should just be idempotent, and we should relegate lookup misses to a warning.

**Comment by HeavyWombat** [comment]
I like the idea. I remember we had a similar discussion some time ago and there was an idea to (kind of) solve that using a twist by introducing reg-ex style Spruce operators that by definition would allow for the different behavior of ignoring the command if there is no match. The issue was #183

**Comment by geofffranks** [comment]
Closing as stale
