### ISSUE TITLE
(( param )) example has an error

### ISSUE THREAD

**Issue by adamkingit** [geofffranks/spruce#241]
[(( param ))](https://github.com/geofffranks/spruce/blob/master/doc/operators.md#-param-) [example](https://play.spruce.cf/#b7944defbd5d987c70c25fcbae1756a8) has error:
```
 1 error(s) detected:  - $.properties.base_domain: What domain will be used for this environment?
```

**Comment by geofffranks** [comment]
Nope, that example is both showing how to use the param operator, and showing what it does - throw an error if the param isn't overridden.
