### ISSUE TITLE
(( calc ... )) can't grab from elsewhere

### ISSUE THREAD

**Issue by jhunt** [geofffranks/spruce#245]
It seems like all `(( calc ... ))` is good for is fixed calculations known at authoring time.

I would love to see something like this:

https://play.spruce.cf/#78fead76f3ab67c0b350054d1ee61ccd

```
---
spruce-1-14:
  days: 3
  hours: (( calc "3 * 24" ))
  minutes: (( calc "3 * 24 * 60" ))
  
hopeful:
  days: 3
  hours_expr: (( concat hopeful.days " * 24" ))
  hours: (( calc hopeful.hours_expr ))
  minutes_expr: (( concat hopeful.days " * 24 * 60" ))
  minutes: (( calc minutes_expr ))
  
ideal:
  days: 3
  hours: (( calc ideal.days * 24 ))
  minutes: (( calc ideal.hours * 60 ))

acceptable:
  days: 3
  # note the lack of a space before the '*' operator
  hours: (( calc acceptable.days "* 24" ))
  minute: (( calc acceptable.hours "* 60" ))
```

**Comment by geofffranks** [comment]
It can currently calc based on references, though the syntax is a little unexpected from normal - references are inside the calc string, so it’s easier to read/write when using the values inside a function:

https://play.spruce.cf/#a069c79eae73a6c9f6b17907a881b808

**Comment by jhunt** [comment]
Perhaps we should document that in the README...

**Comment by geofffranks** [comment]
The calc operator is documented with examples at https://github.com/geofffranks/spruce/blob/master/doc/operators.md#-calc-, which is linked to from the README's Documentation section. If those docs is lacking or confusing in some regard, I'm open to PRs to make things more clear.
