### ISSUE TITLE
mozilla sops support

### ISSUE THREAD

**Issue by prein** [geofffranks/spruce#248]
I have been using spruce in ci/cd pipelines and it was great benefit to have vault support built in. Thank you! 
Recently I came across [mozilla sops](https://github.com/mozilla/sops) and I am planning on using it in my current project. I think sops support would fit spruce well as sops operates on yaml files.

**Comment by geofffranks** [comment]
How would this work? It seems like sops is more of a pre/postprocessor of yaml files, so you would just pipe the spruce merge output into it to encrypt, or decrypt with sops + send to spruce?

**Comment by prein** [comment]
Yes, it's different from vault, there's no calls to any API. Sops processes the files locally. I was thinking of "hiding" the pipe operations in spruce which would make some bash scripting redundant.
Now when I think of it, perhaps not a big win.
