### ISSUE TITLE
"spruce json" might lose data

### ISSUE THREAD

**Issue by sorenh** [geofffranks/spruce#259]
A comment on #258 raised a concern about json conversion losing data:
```
me@host: cat file.yml
tags:
  v4: old
  v4.b4: new
  v4.b4.p4: newer
  v4.b4.p4.c4: newest
versions:
  "4": value for 4 with quote
  4: value for 4 no quote
  "4.4": new
  4.4.4: newer
  4.4.4.4: newest

me@host: spruce json file.yml | spruce merge
tags:
  v4: old
  v4.b4: new
  v4.b4.p4: newer
  v4.b4.p4.c4: newest
versions:
  "4": value for 4 no quote
  "4.4": new
  4.4.4: newer
  4.4.4.4: newest
```

JSON keys are always strings. YAML keys can be any type. So when we convert from YAML to JSON, we might have two keys that are identical when turned into strings and since keys must be unique, we can lose data.

**Comment by sorenh** [comment]
A couple of suggestions:

Issue a warning if this happens.

Refuse to turn a yaml doc into JSON if it has non-string keys. (some sort of extra strict mode)

**Comment by ywei2017** [comment]
Now I understand my issue better. I didn't know that yaml keys can be any data type.  In addition to what @sorenh said, how about another option/switch saying "when converting from json to yaml, try to convert keys to numbers if possible, or treat all keys as strings"?

**Comment by sorenh** [comment]
All keys ARE treated as strings. In JSON all keys are strings and they are treated as such during conversion to YAML.
