### ISSUE TITLE
canonicalize operators before evaluating equivalence for merge

### ISSUE THREAD

**Issue by thomasmitchell** [geofffranks/spruce#270]
https://play.spruce.cf/#a4919bb224de68042f23864ad1ce8131

When array merging is evaluating whether to merge two keys, it is doing literal comparison (which is mostly all it can do considering how early in the process it is). However, sometimes, you want to merge two things which will become the same value because they are evaluating the same operator. This works fine in the case that you have formatted the operator the same in both instances, but if the spacing is different, it won't be a string match.

This is a humble request that when checking for merge key equivalence, if an operator is detected, it is canonicalized such that they would match in this case. This is more for making this admittedly niche operation more intuitive, and the obvious workaround as it works currently is to eventually just... reformat one of the keys to match the other.

**Comment by geofffranks** [comment]
Closing as stale
