### ISSUE TITLE
(( prune )) doesn't work for keys containing dots

### ISSUE THREAD

**Issue by bgandon** [geofffranks/spruce#271]
When I try to prune a key that contains a dot (`.`), Spruce does not prune it properly.

````yaml
operations_files:
  10.local: (( prune )) # doesn't work: the key is kept in the 'spruce merge' result
````

If I rename the key with a dash (`-`) instead on the dot (`.`), then the key is properly pruned.

````yaml
operations_files:
  10-local: (( prune )) # works: the key is pruned from the 'spruce merge' result
````

For this test, I'm using the latest spruce v1.18.2.
I guess the issue is related to the dot (`.`) being a separator with a special meaning in spruce.

Hope you can fix it, or document this behavior as a caveat somewhere.

Best,
Benjamin

**Comment by HeavyWombat** [comment]
I once played around with a possible fix to ease this problem a little bit, but I was not very happy with the solution. Basically it used something like URL-encoding for the names used by the internals inside of the dependency project that deals with the tree structure.

Anyway, one thing we use to come around this issue if you have no option to change the key, is to outsource the pruning to another file that uses GoPatch syntax to delete the respective part of your document.

**Comment by bgandon** [comment]
Thank you for this answer, Matthias.
Then we need to find a place where to document this caveat!

**Comment by geofffranks** [comment]
https://github.com/geofffranks/spruce/blob/master/doc/operators.md#operator-arguments or https://github.com/geofffranks/spruce/blob/master/doc/operators.md#-prune- might be good spots for it?

**Comment by HeavyWombat** [comment]
I would opt for documenting it in the main operator description document since this is a general issue for multiple operators ([grab example](https://play.spruce.cf/#d3999df9689aaa90db0e215c488191d9)). I will open a PR shortly.

**Comment by geofffranks** [comment]
Closing as stale
