### ISSUE TITLE
merge mangles up when value contains comma

### ISSUE THREAD

**Issue by ywei2017** [geofffranks/spruce#280]
I can swear this worked in the past, and then suddenly it stopped working. When the default value in grab contains ',', the result gets a new line.

```
#cat file2.json
{"meta":{"key1": (( grab meta.key2 || "default,value" )) }}
#spruce merge file2.json
meta:
  key1: (( grab meta.key2 || "default
  value" )): null

#
```

I tried with different versions of spruce and they all gave the same result.

**Comment by ywei2017** [comment]
I tried it in the [playground](https://play.spruce.cf/) with the same result using different versions. It is frustrating since I think it worked fine for us until this month. But I have no evidence or logic to back it up, so it sounds I am dreaming it up.

**Comment by geofffranks** [comment]
I believe this is due to bad json syntax triggering odd quote parsing in the yaml parser:

Fails: https://play.spruce.cf/#944e75fac490144208b55feaf66381ee
Works: https://play.spruce.cf/#d4fb98efdbeb85dde68c4cfb70484505
Yaml-ified: https://play.spruce.cf/#944e75fac490144208b55feaf66381ee
