### ISSUE TITLE
Official Dockerfile

### ISSUE THREAD

**Issue by Dargmuesli** [geofffranks/spruce#281]
Is there an official Dockerfile? If not, why not? ;)

**Comment by geofffranks** [comment]
All the times I’ve wanted spruce in a docker image, it was l needed with a bunch of other utilities, but no objections to a PR :)

**Comment by Dargmuesli** [comment]
Would it be enough for now to push only version-numbered Docker images? Or would you like to have something like a `dev` tag for the most recent commit on master (not a **release**).

**Comment by Dargmuesli** [comment]
I went through the CI files of this project and must admit, that I've never seen Concourse before. I can think of two easy ways to add Docker image support: via DockerHub's automated builds or via Travis. I have no idea how to write correct Concourse configs and how to test that (if that's even an option).
Speaking of Travis: what exactly is the purpose of Travis in the first place? As far as I understand it Concourse is in charge of builds, tests and releases, isn't it?

**Comment by geofffranks** [comment]
Travis is used for testing PRs prior to merging, but concourse for the rest currently. I'm curious what you're using spruce for, since it was built originally to make easier the merging config files for BOSH and Concourse together. Will @HeavyWombat's image work for your purposes?

**Comment by Dargmuesli** [comment]
I use spruce to add yml properties for prodction to development Dockerfiles ;)
@HeavyWombat's image works great for me, thanks a lot! One question: the release note says that the image is released as `geofffranks/spruce:v1.19.2` for example. But where? I didn't find it on DockerHub. And also my name isn't written correctly in the release note, but I don't take that personal 😂

**Comment by geofffranks** [comment]
Apparently i don't know my own dockerhub id. It's actually at `gfranks/spruce` (release notes have been updated).

Also your name was always spelled right in the release notes, I don't now what you're talking about... ;)

**Comment by Dargmuesli** [comment]
🚀
