### ISSUE TITLE
Spruce diff does not show the changes in array order if array element is a hash

### ISSUE THREAD

**Issue by b10s** [geofffranks/spruce#285]
```
$ cat foo.yml 
foo:
  - name: one
    prop: one
  - name: two
    prop: two
  - name: three
    prop: three

$ cat bar.yml 
foo:
  - name: one
    prop: one
  - name: three
    prop: three
  - name: two
    prop: two

$ spruce diff foo.yml bar.yml 
both files are semantically equivalent; no differences found!
```

**Comment by HeavyWombat** [comment]
A very long time ago I had a conversation about the diff command in Slack. I do not recall the reason anymore. After that I started a side project to write a replacement for the spruce diff command, but at the end never PR'ed it.

It works nicely as a standalone command, if someone wants to give it a try: https://github.com/HeavyWombat/dyff. Unlike the spruce diff, the order of list entries is taken into consideration. It heavily borrows from the old BOSH v1 diff style.

![image](https://user-images.githubusercontent.com/1979133/54076364-3e164b00-42ab-11e9-9a6b-3688f1f88e7e.png)

@geofffranks @jhunt I am not sure how heavily that `diff` feature is used, but if you think it is worth it I can have a look into PR'ing it. One of the reasons I never PR'ed it was that it breaks completely with the current output.

**Comment by geofffranks** [comment]
@HeavyWombat go for it, diffing order of arrays seems like an important thing to solve. I'll take a look at the output and see what I think. Not sure there's anything that automatically looks at diff output, but i could be wrong
