### ISSUE TITLE
move (( empty )) into merge time

### ISSUE THREAD

**Issue by thomasmitchell** [geofffranks/spruce#288]
The following breaks, but it might make more sense for inject to just inject an empty map. Instead, it tries to inject the string `(( empty map ))`, and then it dies. `(( empty ... ))` should probably be moved into a phase where `(( inject ... ))` can see it as a dependency and hold off until the map becomes an actual empty map.

```
---
meta:
  foo:
    beep: boop
    
---
stuff:
  name: geoff
  .: (( inject meta.foo ))
  
---
meta:
  foo: (( empty map ))
```

**Comment by geofffranks** [comment]
closing as stale
