### ISSUE TITLE
Operators composition within same line?

### ISSUE THREAD

**Issue by silomare** [geofffranks/spruce#291]
I'd like to do:
my_var: (( vault concat grab $envvar "<literal_path>:value" ))

I know it can be done through references breaking down the above into
prefix: (( grab $envvar ))
vault_path_ref: (( concat prefix "<literal_path>:value" ))
my_var: (( vault vault_path_ref ))

Is there any construct to achieve the above in one line?
Thanks

**Comment by geofffranks** [comment]
You should be able to just do it all in one:

`(( vault path.to.thing “some strings” $envvar “otherstuff:key” ))`

**Comment by silomare** [comment]
this is great @geofffranks , thanks a lot, it does work
