### ISSUE TITLE
project build status in README is not accessible

### ISSUE THREAD

**Issue by VasylTretiakov** [geofffranks/spruce#316]
![spruce_build_status](https://user-images.githubusercontent.com/3999712/80859177-4ed01000-8c67-11ea-8690-0db46e14e121.png)
seems to be caused by

![ci_522](https://user-images.githubusercontent.com/3999712/80859159-25af7f80-8c67-11ea-8eac-184ecec01738.png)

**Comment by VasylTretiakov** [comment]
Has CI moved to https://pipes.starkandwayne.com? If so, I do not seem to find spruce there...

**Comment by geofffranks** [comment]
It’s on ci.spruce.cf now
