### ISSUE TITLE
Grab command split over multiple lines

### ISSUE THREAD

**Issue by tamanna2702** [geofffranks/spruce#330]
My use case : 

https://play.spruce.cf/#ba206e885042de0b7717e3153afda82e

As you see here, I have a lot of entries to grab which are around 20. And mentioning all of them in a single line doesn't look very clean, so I wanted to know if there is a way I can mention them over new lines like below:

```
fruit:
  name: apple
  key: (( grab $apple 
$grape 
$orange 
$mango))
```
 
The above doesn't work, but is there a way to have it over separate lines as I have a lot of entries?

**Comment by geofffranks** [comment]
closing as stale
