### ISSUE TITLE
Support an inject mechanism

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#48]
spiff's custom yaml parser allowed for `<<: (( thing ))` to pull in attributes from thing, and place them in the parent. Since spruce is using goyaml, and `<<:` is actually a YAML construct when used with YAML anchors, we can't use this with spruce.

Implement an `(( inject stuff ))` operator so this is once again possible.

**Comment by geofffranks** [comment]
@longnguyen11288 are you happy with the inject support that exists on origin/master? Any bugs need fixing?

**Comment by longnguyen11288** [comment]
no

**Comment by filefrog** [comment]
no you are not happy?  or no, no more bugs?

**Comment by longnguyen11288** [comment]
no more bugs for now, maybe some tomorrow
