### ISSUE TITLE
concat fails when square brackets contains colon

### ISSUE THREAD

**Issue by ssurenr** [geofffranks/spruce#59]
When `concat` is used within square brackets, and the the concat string contains a colon, spruce merge fails.
For eg.,  
*template.yml*
```yml
---
top: {url: (( concat "https://" some.variable  ".com" ))}
```
*properties.yml*
```yml
---
some:
  variable: example
```  
`spruce merge properties.yml template.yml` results in the following error
`template.yml: unmarshal []byte to yaml failed: yaml: line 1: found unexpected ':'`

**Comment by geofffranks** [comment]
I don't think that's valid YAML. Try single-quoting the `url` key's value to fix it:
```
---
top: {url: '(( concat "https://" some.variable  ".com" ))'}
some:
  variable: example
```
