### ISSUE TITLE
non-helpful error message on missing param

### ISSUE THREAD

**Issue by cromega** [geofffranks/spruce#70]
```
1 error(s) detected:
 - $.jobs.cluster_monitor.properties.nats-to-syslog.nats.password: BOSH NATS password
```

for `(( param "BOSH NATS password" ))`

Luckily I knew what was wrong because I was testing my stubs but a slightly more useful error message would be immensely helpful for users who don't actually know what's in the stubs.

**Comment by cromega** [comment]
I just realised I could write `(( param "BOSH NATS password is required" ))` for that effect :)
Feel free to close this issue if you think it's a non-issue.

**Comment by filefrog** [comment]
Yeah, the normal use case for `(( param ... ))` is to provide the error message yourself, as you found.
