### ISSUE TITLE
require explicit override with null

### ISSUE THREAD

**Issue by cromega** [geofffranks/spruce#71]
stub1.yml:
```
baz:
  foo:
    bar: (( param "I need a bar" ))
```

stub2.yml:
```
baz:
  foo:
```

```
$ spruce merge stub1.yml stub2.yml
baz:
  foo: null
```

I expected the missing param `bar` to cause an error.

I think if I wanted the result to be what I pasted above I should have to have the following in stub2.yml

```
baz:
  foo: ~
```

What do you think?

**Comment by filefrog** [comment]
Spruce follows the semantics of YAML closely, and YAML sees `foo: ` as equivalent to `foo: null`:

```
→  echo "foo: " | yaml2json
{"foo":null}
```
