### ISSUE TITLE
Release binaries structure

### ISSUE THREAD

**Issue by haydonryan** [geofffranks/spruce#97]
Hey,
I'm setting up a jumpbox provisioner script.   Is there an automatic way to download the 'latest' version of spiff without installing go?

Haydon

**Comment by jhunt** [comment]
Well, I hope you mean spruce, and not spiff... :smile:

We normally use the Releases page to download the zip file: https://github.com/geofffranks/spruce/releases

see https://github.com/jhunt/jumpbox/blob/master/bin/jumpbox#L97-L106

**Comment by haydonryan** [comment]
Sorry did mean Spruce

That doesn't really fix the 'get latest version' without knowing what that version is though... ;)

**Comment by jhunt** [comment]
Yeah, sadly that's the best we have right now.

**Comment by drnic** [comment]
Yay @starkandwayne-bot 

```
spruce_1.0.1_darwin_amd64.zip  
spruce_1.0.1_linux_386.tar.gz  
spruce_1.0.1_linux_amd64.tar.gz  
```

Why is the `darwin` download a zip file; but the others are `tar.gz`?

**Comment by haydonryan** [comment]
Thanks Guys :) Appreciate it.
